# Generated by Django 5.0.6 on 2024-06-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotareadb',
            name='progreso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Progreso'),
        ),
    ]
